package org.geotools.jdbc;


/**
 * Represents a column of a primary key whose values are auto generated 
 * by the database.
 * <p>
 * This class does not generate new values for the key, relying on the 
 * database to do so.
 * </p>
 * @author Justin Deoliveira, OpenGEO
 *
 */
public class AutoGeneratedPrimaryKeyColumn extends PrimaryKeyColumn {

    public AutoGeneratedPrimaryKeyColumn(String name, Class type) {
        super(name, type);
    }

}
