package org.geotools.jdbc;


/**
 * Represents a column of a primary key which has an associated sequence
 * used to generate its values.
 * <p>
 * New values for the key are generated by selecting the next value of the 
 * sequence.
 * </p>
 * @author Justin Deoliveira, OpenGEO
 *
 */
public class SequencedPrimaryKeyColumn extends PrimaryKeyColumn {

    String sequenceName;
    
    public SequencedPrimaryKeyColumn(String name, Class type, String sequenceName) {
        super(name, type);
        this.sequenceName = sequenceName;
    }

    public String getSequenceName() {
        return sequenceName;
    }
    
//    @Override
//    public Object generate(Connection cx, SQLDialect dialect)
//            throws SQLException, IOException {
//        return dialect.getNextValueFromSequence( sequence, cx );
//    }

}
