package org.geotools.data.ingres;

import org.geotools.jdbc.JDBCPrimaryKeyTestSetup;
import org.geotools.jdbc.JDBCTestSetup;

public class IngresPrimaryKeyTestSetup extends JDBCPrimaryKeyTestSetup {

	protected IngresPrimaryKeyTestSetup(JDBCTestSetup delegate) {
		super(delegate);
		// TODO Auto-generated constructor stub
	}

	@Override
	protected void createAutoGeneratedPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void createMultiColumnPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void createNonIncrementingPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void createNullPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void createSequencedPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void createUniqueIndexTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void dropAutoGeneratedPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void dropMultiColumnPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void dropNonIncrementingPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void dropNullPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void dropSequencedPrimaryKeyTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void dropUniqueIndexTable() throws Exception {
		// TODO Auto-generated method stub
		
	}

}
