/*
 * JSimpleDialog.java
 *
 * Created on 17 mai 2008, 20:17
 */

package org.geotools.gui.swing.style.sld;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import org.geotools.gui.swing.icon.IconBundle;

/**
 *
 * @author  sorel
 */
public class JSimpleDialog extends javax.swing.JDialog {

    private static final ImageIcon ICO_CLOSE = IconBundle.getResource().getIcon("16_close");
    
    /** Creates new form JSimpleDialog */
    public JSimpleDialog(java.awt.Frame parent, boolean modal,Component child) {
        super(parent, modal);
        initComponents();
        
        guiBar.setLayout(new FlowLayout(FlowLayout.RIGHT));
        
        JScrollPane jsp = new JScrollPane(child);
        
        add(BorderLayout.CENTER,jsp);
        add(BorderLayout.SOUTH,guiBar);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiBar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        guiBar.setFloatable(false);
        guiBar.setRollover(true);

        jButton1.setIcon(ICO_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/geotools/gui/swing/propertyedit/Bundle"); // NOI18N
        jButton1.setText(bundle.getString("close")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        guiBar.add(jButton1);

        getContentPane().add(guiBar, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar guiBar;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
