/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 */
package org.geotools.vpf;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

/**
 * File <code>RowFieldTest.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" org.geotools.vpf.RowFieldTest
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class RowFieldTest extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected RowField varRowField;

  /**
   * Public constructor for creating testing class.
   */
  public RowFieldTest(String name) {
    super(name);
  } // end of RowFieldTest(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    // Initialize your variable(s) here
    // for example:
    // varRowField = new RowField(...);
    // But note that there is no default constructor in RowField
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(RowFieldTest.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing original source method:
   * double getAsDouble()
   * from tested class
   */
  public void testGetAsDouble() {
    double[] testVals = {Double.MAX_VALUE, Double.MIN_VALUE, Double.NaN,
                         Double.NEGATIVE_INFINITY, Double.POSITIVE_INFINITY, 0};
    for (int i = 0; i < testVals.length; i++)
    {
      varRowField = new RowField(new Double(testVals[i]), ' ');
      assertEquals("Test RowField for value: "+testVals[i],
                   testVals[i], varRowField.getAsDouble(), 0);
    } // end of for (int i = 0; i < testVals.length; i++)
  } // end of testGetAsDouble()

  /**
   * Method for testing original source method:
   * float getAsFloat()
   * from tested class
   */
  public void testGetAsFloat() {
    float[] testVals = {Float.MAX_VALUE, Float.MIN_VALUE, Float.NaN,
                         Float.NEGATIVE_INFINITY, Float.POSITIVE_INFINITY, 0};
    for (int i = 0; i < testVals.length; i++)
    {
      varRowField = new RowField(new Float(testVals[i]), ' ');
      assertEquals("Test RowField for value: "+testVals[i],
                   testVals[i], varRowField.getAsFloat(), 0);
    } // end of for (int i = 0; i < testVals.length; i++)
  } // end of testGetAsFloat()

  /**
   * Method for testing original source method:
   * int getAsInt()
   * from tested class
   */
  public void testGetAsInt() {
    int[] testVals = {Integer.MAX_VALUE, Integer.MIN_VALUE, 0};
    for (int i = 0; i < testVals.length; i++)
    {
      varRowField = new RowField(new Integer(testVals[i]), ' ');
      assertEquals("Testing RowField for value: "+testVals[i],
                   testVals[i], varRowField.getAsInt());
    } // end of for (int i = 0; i < testVals.length; i++)
  } // end of testGetAsInt()

  /**
   * Method for testing original source method:
   * long getAsLong()
   * from tested class
   */
  public void testGetAsLong() {
    long[] testVals = {Long.MAX_VALUE, Long.MIN_VALUE, 0};
    for (int i = 0; i < testVals.length; i++)
    {
      varRowField = new RowField(new Long(testVals[i]), ' ');
      assertEquals("Testing RowField for value: "+testVals[i],
                   testVals[i], varRowField.getAsLong());
    } // end of for (int i = 0; i < testVals.length; i++)
  } // end of testGetAsLong()

  /**
   * Method for testing original source method:
   * short getAsShort()
   * from tested class
   */
  public void testGetAsShort() {
    short[] testVals = {Short.MAX_VALUE, Short.MIN_VALUE, 0};
    for (int i = 0; i < testVals.length; i++)
    {
      varRowField = new RowField(new Short(testVals[i]), ' ');
      assertEquals("Testing RowField for value: "+testVals[i],
                   testVals[i], varRowField.getAsShort());
    } // end of for (int i = 0; i < testVals.length; i++)
  } // end of testGetAsShort()

  /**
   * Method for testing original source method:
   * java.lang.String getAsString()
   * from tested class
   */
  public void testGetAsString() {
    String[] testVals = {null, "", "\0", "\n", "                       "};
    for (int i = 0; i < testVals.length; i++)
    {
      varRowField = new RowField(testVals[i], ' ');
      assertEquals("Testing RowField for value: "+testVals[i],
                   testVals[i], varRowField.getAsString());
    } // end of for (int i = 0; i < testVals.length; i++)
  } // end of testGetAsString()

  /**
   * Method for testing original source method:
   * char getType()
   * from tested class
   */
  public void testGetType() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testGetType()

  /**
   * Method for testing original source method:
   * java.lang.Object getValue()
   * from tested class
   */
  public void testGetValue() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testGetValue()

  /**
   * Method for testing original source method:
   * java.lang.String toString()
   * from tested class
   */
  public void testToString() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testToString()

} // end of RowFieldTest
