/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 *
 *    (C) 2007-2009, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

// This code has been generated by the code Wizard and should not be
// modified.  The recommended manner of changing the behavior is to
// implement a class that inherits from this generated class.
package org.geotools.process.idl.impl;

import com.idl.javaidl.JIDLConst;
import com.idl.javaidl.JIDLString;

/**
 * IDL FeatureExtraction operation Wrapper. 
 */
public class IDLFeatureExtractionWrapper extends BaseIDLObjectWrapper{
    private static final long serialVersionUID = 6560909290441349623L;
    // Constants set by Wizard
    private static String IDL_CLASS = "psg_fx";

    // Constructor
    public IDLFeatureExtractionWrapper(final String processName) {
       super(IDL_CLASS,processName);
    }

    // properties generated by Wizard

    // class methods generated by Wizard

    public JIDLString _IDL__FEATUREEXTRACTION(
       JIDLString FILENAME){
       final int ARGC = 1;
       Object[] argv = new Object[ARGC];
       int[] argp = new int[ARGC];

       Object result = null;
       final int FLAGS = 0;

       // Parameter assignments
       argv[0] = FILENAME;
       argp[0] = JIDLConst.PARMFLAG_CONST;

       result = super.callFunction("__IDL_EXECUTE", ARGC, argv, argp, FLAGS);
       return (JIDLString)result;
    }
}
