/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 */
package org.geotools.vpf.util;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

/**
 * File <code>DataUtilsTest.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" org.geotools.vpf.util.DataUtilsTest
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class DataUtilsTest extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected DataUtils varDataUtils;

  /**
   * Public constructor for creating testing class.
   */
  public DataUtilsTest(String name) {
    super(name);
  } // end of DataUtilsTest(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
        public void eventDispatched(AWTEvent event) {
          WindowEvent we = ((WindowEvent) event);
          if (we.getID() == WindowEvent.WINDOW_OPENED)
            we.getWindow().dispose();
        }
      }, AWTEvent.WINDOW_EVENT_MASK);
    varDataUtils = new org.geotools.vpf.util.DataUtils();
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(DataUtilsTest.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing original source method:
   * int bigEndianToInt(byte[])
   * from tested class
   */
  public void testBigEndianToInt1374008726() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testBigEndianToInt1374008726(byte[])

  /**
   * Method for testing original source method:
   * java.lang.Object decodeData(byte[], char)
   * from tested class
   */
  public void testDecodeData13740087263052374() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testDecodeData13740087263052374(byte[], char)

  /**
   * Method for testing original source method:
   * double decodeDouble(byte[])
   * from tested class
   */
  public void testDecodeDouble1374008726() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testDecodeDouble1374008726(byte[])

  /**
   * Method for testing original source method:
   * float decodeFloat(byte[])
   * from tested class
   */
  public void testDecodeFloat1374008726() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testDecodeFloat1374008726(byte[])

  /**
   * Method for testing original source method:
   * int decodeInt(byte[])
   * from tested class
   */
  public void testDecodeInt1374008726() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testDecodeInt1374008726(byte[])

  /**
   * Method for testing original source method:
   * short decodeShort(byte[])
   * from tested class
   */
  public void testDecodeShort1374008726() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testDecodeShort1374008726(byte[])

  /**
   * Method for testing original source method:
   * int littleEndianToInt(byte[])
   * from tested class
   */
  public void testLittleEndianToInt1374008726() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testLittleEndianToInt1374008726(byte[])

  /**
   * Method for testing original source method:
   * byte[] toBigEndian(byte[])
   * from tested class
   */
  public void testToBigEndian1374008726() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testToBigEndian1374008726(byte[])

  /**
   * Method for testing original source method:
   * int unsigByteToInt(byte)
   * from tested class
   */
  public void testUnsigByteToInt3039496() {

    assertTrue("Warning! This is new test method with no real test code inside.", false);

  } // end of testUnsigByteToInt3039496(byte)

} // end of DataUtilsTest
