/* Generated By:JJTree: Do not edit this line. ExpressionParserTreeConstants.java */

package org.geotools.filter.parser;

public interface ExpressionParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTORNODE = 1;
  public int JJTANDNODE = 2;
  public int JJTEQNODE = 3;
  public int JJTNENODE = 4;
  public int JJTBETWEENNODE = 5;
  public int JJTLTNODE = 6;
  public int JJTGTNODE = 7;
  public int JJTLENODE = 8;
  public int JJTGENODE = 9;
  public int JJTADDNODE = 10;
  public int JJTSUBTRACTNODE = 11;
  public int JJTMULNODE = 12;
  public int JJTDIVNODE = 13;
  public int JJTNOTNODE = 14;
  public int JJTATTNODE = 15;
  public int JJTINTEGERNODE = 16;
  public int JJTFLOATINGNODE = 17;
  public int JJTTRUENODE = 18;
  public int JJTFALSENODE = 19;
  public int JJTSTRINGNODE = 20;
  public int JJTFUNCTIONNODE = 21;
  public int JJTWKTNODE = 22;


  public String[] jjtNodeName = {
    "void",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "BetweenNode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "NotNode",
    "AttNode",
    "IntegerNode",
    "FloatingNode",
    "TrueNode",
    "FalseNode",
    "StringNode",
    "FunctionNode",
    "WKTNode",
  };
}
