/* Generated By:JJTree: Do not edit this line. ExpressionParserVisitor.java */

package org.geotools.filter.parser;

public interface ExpressionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
