/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */
package org.geotools.filter.parser;

public interface ExpressionParserConstants {

  int EOF = 0;
  int SQ_STRING = 8;
  int DQ_STRING = 9;
  int AND = 12;
  int OR = 13;
  int NOT = 14;
  int EQ = 15;
  int NEQ = 16;
  int GT = 17;
  int LT = 18;
  int GTE = 19;
  int LTE = 20;
  int TRUE = 21;
  int FALSE = 22;
  int POINT = 23;
  int LINESTRING = 24;
  int POLYGON = 25;
  int MULTIPOINT = 26;
  int MULTILINESTRING = 27;
  int MULTIPOLYGON = 28;
  int GEOMETRYCOLLECTION = 29;
  int LP = 30;
  int RP = 31;
  int LSP = 32;
  int RSP = 33;
  int IDENTIFIER = 34;
  int INTEGER_LITERAL = 35;
  int FLOATING_LITERAL = 36;
  int LETTER = 37;
  int DIGIT = 38;
  int EXPONENT = 39;

  int DEFAULT = 0;
  int IN_SQ = 1;
  int IN_DQ = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<EQ>",
    "<NEQ>",
    "<GT>",
    "<LT>",
    "<GTE>",
    "<LTE>",
    "\"true\"",
    "\"false\"",
    "\"point\"",
    "\"linestring\"",
    "\"polygon\"",
    "\"multipoint\"",
    "\"multilinestring\"",
    "\"multipolygon\"",
    "\"geometrycollection\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "<FLOATING_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "<EXPONENT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
  };

}
