/* Generated By:JJTree: Do not edit this line. /home/en/oms/gt2nb/src/org/geotools/modules/gtcore/expressions/ExpressionParserVisitor.java */

package org.geotools.filter.parser;

public interface ExpressionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
