/*
 * MapViewer3.java
 *
 * Created on 18 August 2002, 21:11
 */

package org.geotools.demos;

import java.awt.Rectangle;
import java.io.File;
import java.util.logging.Logger;
import java.io.IOException;
import javax.swing.JFileChooser;
import org.geotools.data.DataSource;
import org.geotools.data.DataSourceException;
import org.geotools.gml.GMLDataSource;
import org.geotools.gui.swing.MapPane2;
import org.geotools.gui.tools.Tool;
import org.geotools.gui.tools.PanTool;
import org.geotools.map.AreaOfInterestModel;
import org.geotools.map.DefaultAreaOfInterestModel;
import org.geotools.map.Layer;
import org.geotools.map.LayerList;
import org.geotools.map.DefaultLayer;
import org.geotools.map.DefaultLayerList;
import org.geotools.styling.SLDStyle;

/**
 *
 * @author  Cameron Shorter
 */
public class MapViewer3 extends javax.swing.JFrame {

    /** Creates new form MapViewer3 */
    public MapViewer3() {
        initComponents();
    }

    /**
     * The class used for identifying for logging.
     */
    private static final Logger LOGGER = Logger.getLogger("org.geotools.demos");

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        AreaOfInterestModel areaOfInterestModel = new DefaultAreaOfInterestModel(null,null);
        LayerList layerList = new DefaultLayerList();
        File f=new File("/home/cameron/work/geotools2/geotools-src/sldstyling/tests/unit/testData/sample.sld");
        try {
            GMLDataSource datasource = new GMLDataSource("http://localhost/geotools2/geotools-src/svgsupport/tests/unit/testData/simple.gml");
            SLDStyle style = new SLDStyle(f.toURL());
            //SLDStyle style=getStyle();
            Layer layer=new DefaultLayer(datasource,style);
            layer.setTitle("funky layer");
            layerList.addLayer(layer);
        } catch (Exception e){
            LOGGER.warning("Exception: "+e+".  Unable to load GML.");
        }
        Tool tool=new PanTool();
        MapPane2 mapPane = new MapPane2(
            tool,
            layerList,
            areaOfInterestModel);
        mapPane.setMapSize(new Rectangle(100,100));

        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jToggleButton2.setText("jToggleButton2");
        mapPane.setSize(200,200);
        mapPane.setViewportView(jToggleButton2);

        getContentPane().add(mapPane, java.awt.BorderLayout.CENTER);

        jToggleButton1.setText("Pan");
        getContentPane().add(jToggleButton1, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);
        setJMenuBar(jMenuBar1);

        pack();
    }

     private SLDStyle getStyle(){
        try{
            JFileChooser fc = new JFileChooser();
            int status = fc.showOpenDialog(this);
            if(status != JFileChooser.APPROVE_OPTION){
                return null;
            }
            File f = fc.getSelectedFile();
            SLDStyle style = new SLDStyle(f.toURL());
            return style;
        }
        catch(IOException ioe){
            LOGGER.warning("Unable to load SLD file");
            return null;
        }
     }
     
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new MapViewer3().show();
    }


    // Variables declaration - do not modify
    private MapPane2 mapPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration

}
