/*
 * MapViewer2.java
 *
 * Created on 05 September 2002, 07:25
 */

package org.geotools.demos;

import java.net.URL;
import java.awt.Rectangle;
import java.io.File;
import java.io.IOException;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.geotools.data.DataSource;
import org.geotools.data.DataSourceException;
import org.geotools.gml.GMLDataSource;
import org.geotools.gui.swing.MapPane2;
import org.geotools.gui.tools.PanTool;
import org.geotools.gui.tools.Tool;
import org.geotools.map.AreaOfInterestModel;
import org.geotools.map.DefaultAreaOfInterestModel;
import org.geotools.map.DefaultLayer;
import org.geotools.map.DefaultLayerList;
import org.geotools.map.Layer;
import org.geotools.map.LayerList;
import org.geotools.styling.SLDStyle;

/**
 *
 * @author  cameron
 */
public class MapViewer2 extends javax.swing.JFrame {

    /**
     * The class used for identifying for logging.
     */
    private static final Logger LOGGER = Logger.getLogger("org.geotools.demos");

    /** Creates new form MapViewer2 */
    public MapViewer2() {
        LOGGER.info("mapViewer graphics="+this.getGraphics());
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents

    /** 
     * Extra initialisation.
     */
    private void initComponents2() {
        AreaOfInterestModel areaOfInterestModel = new DefaultAreaOfInterestModel(null,null);
        LayerList layerList = new DefaultLayerList();
        try {
           GMLDataSource datasource = new GMLDataSource(
                ClassLoader.getSystemResource("org/geotools/demos/simple.gml"));
            SLDStyle style = new SLDStyle(
                ClassLoader.getSystemResource("org/geotools/demos/simple.sld"));
            Layer layer=new DefaultLayer(datasource,style);
            layer.setTitle("funky layer");
            layerList.addLayer(layer);
        } catch (Exception e){
            LOGGER.warning("Exception: "+e+".  Unable to load GML.");
        }
        Tool tool=new PanTool();
        MapPane2 mapPane = new MapPane2(
            tool,
            layerList,
            areaOfInterestModel);
        mapPane.setMapSize(new Rectangle(300,300));

        mapPane.setBorder(new javax.swing.border.TitledBorder("MapPane Map"));
        getContentPane().add(mapPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 420));
        //mapPane.setSize(400,400);
        pack();
    }

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new MapViewer2().show();
    }

    private MapPane2 mapPane;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
